package it.cnr.istc.iloc.gui;

import java.awt.event.ActionEvent;
import javax.swing.Timer;

/**
 *
 * @author Riccardo De Benedictis
 */
public class JStatusBar extends javax.swing.JPanel {

    private static final int DELAY = 10_000;
    private Timer temp;

    /**
     * Creates new form JStatusBar
     */
    public JStatusBar() {
        initComponents();
        busyBar.setVisible(false);
    }

    public void setTempMessage(String message) {
        if (temp != null) {
            temp.stop();
        }
        tempMessageJLabel.setText(message);
        temp = new Timer(DELAY, (ActionEvent ae) -> {
            tempMessageJLabel.setText(null);
            temp.stop();
            temp = null;
        });
        temp.start();
    }

    public void setTaskMessage(String message) {
        taskMessageJLabel.setText(message);
    }

    public void setIndeterminate(boolean indeterminate) {
        busyBar.setVisible(indeterminate);
        busyBar.setIndeterminate(indeterminate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        tempMessageJLabel = new javax.swing.JLabel();
        spaceJLabel = new javax.swing.JLabel();
        taskMessageJLabel = new javax.swing.JLabel();
        busyBar = new javax.swing.JProgressBar();

        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        add(tempMessageJLabel, gridBagConstraints);

        spaceJLabel.setText(" ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        add(spaceJLabel, gridBagConstraints);

        taskMessageJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        add(taskMessageJLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 4);
        add(busyBar, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar busyBar;
    private javax.swing.JLabel spaceJLabel;
    private javax.swing.JLabel taskMessageJLabel;
    private javax.swing.JLabel tempMessageJLabel;
    // End of variables declaration//GEN-END:variables
}
