package it.cnr.istc.iloc.gui.dynamiccausalgraph;

import it.cnr.istc.iloc.api.ISolver;
import it.cnr.istc.iloc.gui.SolverManager;
import it.cnr.istc.iloc.gui.SolverManagerListener;
import java.beans.Beans;
import javax.swing.JInternalFrame;

/**
 *
 * @author Riccardo De Benedictis
 */
public class DynamicCausalGraphJInternalFrame extends JInternalFrame implements SolverManagerListener {

    private ISolver solver;

    /**
     * Creates new form DynamicCausalGraphJInternalFrame
     */
    public DynamicCausalGraphJInternalFrame() {
        initComponents();
        if (!Beans.isDesignTime()) {
            SolverManager.getInstance().addSolverManagerListener(this);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dynamicCausalGraphViewer = new it.cnr.istc.iloc.gui.dynamiccausalgraph.DynamicCausalGraphViewer();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Dynamic causal graph");

        dynamicCausalGraphViewer.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dynamicCausalGraphViewer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dynamicCausalGraphViewer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private it.cnr.istc.iloc.gui.dynamiccausalgraph.DynamicCausalGraphViewer dynamicCausalGraphViewer;
    // End of variables declaration//GEN-END:variables

    @Override
    public void solverChanged(ISolver solver) {
        if (this.solver != null) {
            this.solver.getDynamicCausalGraph().removeCausalGraphListener(dynamicCausalGraphViewer);
        }
        this.dynamicCausalGraphViewer.init();
        this.solver = solver;
        this.solver.getDynamicCausalGraph().addCausalGraphListener(dynamicCausalGraphViewer);
    }
}
