package it.cnr.istc.iloc.gui.statistics;

import it.cnr.istc.iloc.api.ISolver;
import it.cnr.istc.iloc.gui.SolverManager;
import it.cnr.istc.iloc.gui.SolverManagerListener;
import java.beans.Beans;
import javax.swing.JInternalFrame;

/**
 *
 * @author Riccardo De Benedictis
 */
public class StatisticsJInternalFrame extends JInternalFrame implements SolverManagerListener {

    private ISolver solver;

    /**
     * Creates new form StatisticsJInternalFrame
     */
    public StatisticsJInternalFrame() {
        initComponents();
        if (!Beans.isDesignTime()) {
            SolverManager.getInstance().addSolverManagerListener(this);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statisticsChart = new it.cnr.istc.iloc.gui.statistics.StatisticsChart();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Statistics");

        javax.swing.GroupLayout statisticsChartLayout = new javax.swing.GroupLayout(statisticsChart);
        statisticsChart.setLayout(statisticsChartLayout);
        statisticsChartLayout.setHorizontalGroup(
            statisticsChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 676, Short.MAX_VALUE)
        );
        statisticsChartLayout.setVerticalGroup(
            statisticsChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statisticsChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statisticsChart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private it.cnr.istc.iloc.gui.statistics.StatisticsChart statisticsChart;
    // End of variables declaration//GEN-END:variables

    @Override
    public void solverChanged(ISolver solver) {
        if (this.solver != null) {
            this.solver.removeSolverListener(statisticsChart);
        }
        this.statisticsChart.init();
        this.solver = solver;
        this.solver.addSolverListener(statisticsChart);
    }
}
